### ISSUE TITLE
Latest version does not run: Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by mcat95** [StephanGeorg/node-dig-dns#11]
Hello, after upgrading to the latest package version, the package crashes when importing it. We get the following error
```
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /home/marco/testdns/node_modules/node-dig-dns/dist/index.js
- /home/marco/testdns/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/marco/testdns/node_modules/node-dig-dns/dist/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/marco/testdns/node_modules/node-dig-dns/dist/index.js',
    '/home/marco/testdns/test.js'
  ]
}
```

**Comment by StephanGeorg** [comment]
@mcat95 Thanks for reporting. Fixed in npm node-dig-dns@0.2.12
